# Generated by Django 5.1.2 on 2024-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='configuracion',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
