# Generated by Django 5.1.2 on 2024-10-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_configuracion_alter_event_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
