# Generated by Django 5.1.2 on 2024-10-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_configuracion_alter_event_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('estado', models.CharField(default='disponible', max_length=20)),
                ('numero', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sillas', to='event.event')),
            ],
        ),
    ]
