# Generated by Django 5.1.2 on 2024-10-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_silla'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Silla',
            new_name='chair',
        ),
    ]
