# Generated by Django 5.1.2 on 2024-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_silla_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='x',
            new_name='posicion_x',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='y',
            new_name='posicion_y',
        ),
        migrations.RemoveField(
            model_name='chair',
            name='evento',
        ),
        migrations.AlterField(
            model_name='chair',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
