# Generated by Django 5.1.2 on 2024-10-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_x_chair_posicion_x_rename_y_chair_posicion_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='event.event'),
        ),
    ]
