# Generated by Django 4.2.16 on 2024-10-22 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0007_chair_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.chair')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chair', 'id_event')},
            },
        ),
    ]
